"""create Event model

Revision ID: c396330b7807
Revises: 41d9ea6ecffb
Create Date: 2025-07-07 14:26:33.589418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c396330b7807'
down_revision = '41d9ea6ecffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('planning_status', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("planning_status IN ('confirmed', 'tentative')", name='check_planning_status_valid'),
    sa.CheckConstraint('(start_time IS NULL or end_time IS NULL OR start_time <= end_time)', name='check_start_time_before_end_time_or_null'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_events_place_id_places')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_events_trip_id_trips')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_place_association',
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_trip_place_association_place_id_places')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_place_association_trip_id_trips'))
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('trip_place_association')
    op.drop_table('events')
    # ### end Alembic commands ###
